# Generated by Django 4.0.1 on 2023-06-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[['PENDING', 'PENDING'], ['IN_PROGRESS', 'IN_PROGRESS'], ['COMPLETED', 'COMPLETED'], ['CANCELLED', 'CANCELLED']], default='PENDING', max_length=100),
        ),
    ]
